import type {NextPage} from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import CheckboxForm from "../src/components";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app"/>
        <link rel="icon" href="/favicon.ico"/>
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link rel="preconnect" href="https://fonts.gstatic.com"/>
        <link href="https://fonts.googleapis.com/css2?family=Share+Tech+Mono&display=swap" rel="stylesheet"/>
      </Head>

      <main className={styles.main}>
        <CheckboxForm/>
      </main>
    </div>
  )
}

export default Home
